.TH KBOSD 1 "October 29, 2009" "FreeRunner Extra" "KbOSD - Virtual OSD Keyboard"
.SH NAME
kbosd \- Keyboard in OSD
.SH DESCRIPTION
First display an OSD keyboard above the root window, then grab the mouse, then
fake keycode events.
.PP
It will disapear after a short period of inactivity so that you can better see
what you are typing.
.SH ENVIRONMENT
It takes all configuration parameters via environment variables.
The first one are usefull to resize the OSD window so that it does not cover
(and grabs pointer events) some margnis of the screen. The defaults values are
OK for Hackable:1 Freerunner distribution.
.IP \fBKBOSD_BORDER_LEFT\fP 2
Left margin, in pixels, before the OSD window begins (default: 0).
.IP \fBKBOSD_BORDER_RIGHT\fP 2
Right margin, in pixels, after the OSD window (default: 0).
.IP \fBKBOSD_BORDER_TOP\fP 2
Top margin, in pixels, on top of the OSD window (default: 20).
.IP \fBKBOSD_BORDER_BOTTOM\fP 2
Bottom margin, etc (default: 0).
.PP
You can also control the appearance (and disappearance) of the OSD :
.IP \fBKBOSD_COLOR\fP 2
Color as an unsigned integer (for instance, 0xFF0000 on a 32 bits display
would probably be red).
.IP \fBKBOSD_COLOR_ALT\fP 2
Alternate color to use when the special key of scancode 0 is pressed.
.IP \fBKBOSD_TIMEOUT\fP 2
Number of seconds of inactivity before the OSD is hiden (default: 4).
.IP \fBKBOSD_FONT\fP 2
Font to use (default: "-sony-*-*-*-*-*-24-*-*-*-*-*-*-*" which is the
biggest I've found available on H:1).
.IP \fBKBOSD_VIBRATOR_STRENGTH\fP 2
Value from 0 (no vibration) to 255 (max) that defines how much the FreeRunner
will vibrate on each key press. Default is 100.
.IP \fBKBOSD_VIBRATOR_TIME\fP 2
Length in microseconds of the vibration. Default is 50000 (0.05s).
.IP \fBKBOSD_VIBRATOR_FILE\fP 2
Location of the device file kbosd must write to to control the vibrator.
Default to
.B /sys/class/leds/neo1973:vibrator/brightness.
.IP \fBKBOSD_LAYOUT\fP 2
File that describe an alternative layout to use instead of the default one.
See some sample layout in
.BR /prefix/share/kbosd/ .
.SH AUTHORS
rixed@happyleptic.org,
raron@vipmail.hu
